version: "3.8"
services:
  api:
    build: .
    ports:
      - "8086:8086"
    depends_on:
      - db
      - redis
  redis:
    image: redis:7-alpine
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
